apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-check
  labels:
    app: db-check
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-check
  template:
    metadata:
      labels:
        app: db-check
    spec:
      containers:
      - name: db-check
        image: sturrent/dns-monitor:latest