apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-check
  labels:
    app: db-check
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-check
  template:
    metadata:
      labels:
        app: db-check
    spec:
      containers:
      - name: db-check
        image: sturrent/dns-monitor:latest
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload1
  labels:
    app: workload1
spec:
  replicas: 13
  selector:
    matchLabels:
      app: workload1
  template:
    metadata:
      labels:
        app: workload1
    spec:
      containers:
      - name: workload1
        image: sturrent/dns-perf-test-loop:latest
        resources:
          requests:
            memory: "70Mi"
            cpu: "90m"
          limits:
            memory: "700Mi"
            cpu: "1"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload2
  labels:
    app: workload2
spec:
  replicas: 13
  selector:
    matchLabels:
      app: workload2
  template:
    metadata:
      labels:
        app: workload2
    spec:
      containers:
      - name: workload2
        image: sturrent/dns-perf-test-loop:latest
        resources:
          requests:
            memory: "70Mi"
            cpu: "90m"
          limits:
            memory: "700Mi"
            cpu: "1"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload3
  labels:
    app: workload3
spec:
  replicas: 13
  selector:
    matchLabels:
      app: workload3
  template:
    metadata:
      labels:
        app: workload3
    spec:
      containers:
      - name: workload3
        image: sturrent/dns-perf-test-loop:latest
        resources:
          requests:
            memory: "70Mi"
            cpu: "90m"
          limits:
            memory: "700Mi"
            cpu: "1"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
    override-block.server:
       internal.cloudapp.net:53 {
           errors
           cache 30
           forward . /etc/resolv.conf
       }
       reddog.microsoft.com:53 {
           errors
           cache 30
           forward . /etc/resolv.conf
       }